title: "Modelling palaeoecological datasets using a state-space approach: two case-studies"
author:
  - name: Quinn Asena, Jack Williams, and Tony Ives
date: today
bibliography: refs.bib
from: markdown+emoji
embed-resources: true
format:
  revealjs:
    theme: dark
    logo: figures/dark-mode.png
    css: logo.css
#    backgroundcolor: "#44444c"
#    fontcolor: "white"
    preview-links: true
    highlight-style: github
    slide-number: c/t
    width: 1600
    height: 900
title-slide-attributes:
  data-background-color: "#054746ff"

